name: lawod
description: "Splash and Home Screen"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

#---------- PACKAGES ----------#
dependencies:
  flutter:
    sdk: flutter
  scroll_snap_list: ^0.9.1

  # Utility Packages
  camera: ^0.10.5+9
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1
  geocoding: ^2.1.1
  lottie: ^3.0.0
  geolocator: ^10.1.0
  weather_icons: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo.png"

  # Icons
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  hexcolor: ^3.0.1

  # Product Specific

  #---------- PACKAGES ----------#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  #---------- LOCAL ASSETS ----------#
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    -
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNovaBold.ttf
          weight: 700
        - asset: assets/fonts/ProximaNovaRegular.ttf
          weight: 400
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400