// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-L_n-bxGZ1n-wkpGAXaxZtkjgWjo_TRk',
    appId: '1:526075560369:web:64feafaa81904d579dfd90',
    messagingSenderId: '526075560369',
    projectId: 'lawod-c5c76',
    authDomain: 'lawod-c5c76.firebaseapp.com',
    storageBucket: 'lawod-c5c76.appspot.com',
    measurementId: 'G-2EWJFVBGDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOCO3R1XdVwEzuua--1GnioQ-_70Tf4Zo',
    appId: '1:526075560369:android:0098a8801d3eff479dfd90',
    messagingSenderId: '526075560369',
    projectId: 'lawod-c5c76',
    storageBucket: 'lawod-c5c76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoDOpyV6R0yXH9tprostTP2kvsbXuJsPs',
    appId: '1:526075560369:ios:34b7a92716cd3e839dfd90',
    messagingSenderId: '526075560369',
    projectId: 'lawod-c5c76',
    storageBucket: 'lawod-c5c76.appspot.com',
    androidClientId: '526075560369-hv9a8rqvdeuc3ea28kthju4794rnqaa8.apps.googleusercontent.com',
    iosClientId: '526075560369-el0hdgeup5pgoqibof7d5g7g8tl4i9rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoDOpyV6R0yXH9tprostTP2kvsbXuJsPs',
    appId: '1:526075560369:ios:62123c9b39b66d479dfd90',
    messagingSenderId: '526075560369',
    projectId: 'lawod-c5c76',
    storageBucket: 'lawod-c5c76.appspot.com',
    androidClientId: '526075560369-hv9a8rqvdeuc3ea28kthju4794rnqaa8.apps.googleusercontent.com',
    iosClientId: '526075560369-gndg18f205enfvqvjvgbua8p22ml8qao.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawod.RunnerTests',
  );
}
